### ISSUE TITLE
Misspelled column names

### ISSUE THREAD

**Issue by jmenglund** [DINA-Web/dina-collections-data-model#12]
Some column names are misspelled in the schema. Herea are the correct names:

- collected_unit.collected_unit_field_number
- identifiable_unit.belongs_to_physical_unit_id
- observation.observed_by_text
- transcribed_content.is_of_transcribed_content_type

**Comment by jmenglund** [comment]
The column names are now OK, but one foreign key is still misspelled:

`cataloged_unit.takes_place_during_event_id` (referencing `collecting_event.id`)

**Comment by idali0226** [comment]
Fixed

**Comment by jmenglund** [comment]
Checked and OK.
