### ISSUE TITLE
Use "referenced" instead of "source"

### ISSUE THREAD

**Issue by jmenglund** [DINA-Web/dina-collections-data-model#13]
MySQL uses the terms like "referenced_table_schema", "referenced_table_name" and "referenced_column_name". Should we change the column names in [collections-dictionary-columns.csv](https://github.com/DINA-Web/dina-collections-data-model/blob/master/dictionary/collections-dictionary-columns.csv) ("source_schema", "source_table" etc.) accordingly? I think that would improve clarity.

**Comment by jmenglund** [comment]
Should we also remove the "source_data_type" column? I can't see why we need this column.

**Comment by lisasund** [comment]
Ok with me!

**Comment by jmenglund** [comment]
Column names changed and column "source_data_type" removed.
