### ISSUE TITLE
Wrong data type sizes

### ISSUE THREAD

**Issue by jmenglund** [DINA-Web/dina-collections-data-model#15]
The columns listed below has wrong data type sizes. The correct data types are shown within square brackets.

- cataloged_unit.cataloged_by_text [varchar(255)]
- cataloged_unit.id [bigint(20)]
- cataloged_unit.takes_place_during_event_id [bigint(20)]
- collected_unit.id [bigint(20)]
- collected_unit.is_a_result_of_collecting_event_id [bigint(20)]
- collecting_event.event_id [bigint(20)]
- collecting_event.id [bigint(20)]
- event.id [bigint(20)]
- identifiable_unit.belongs_to_cataloged_unit_id [bigint(20)]
- identifiable_unit.belongs_to_physical_unit_id [bigint(20)]
- identifiable_unit.id [bigint(20)]
- identifiable_unit.is_represented_by_individual_group_id [bigint(20)]
- identification.id [bigint(20)]
- identification.observation_id [bigint(20)]
- individual_group.id [bigint(20)]
- individual_group.individual_count [int(11)]
- material_sample.id [bigint(20)]
- material_sample.is_derived_from_collected_unit_id [bigint(20)]
- material_sample.parts_count [int(11)]
- material_sample.physical_unit_id [bigint(20)]
- observation.applies_to_collecting_event_id [bigint(20)]
- observation.applies_to_individual_group_id [bigint(20)]
- observation.id [bigint(20)]
- observation.is_current [tinyint(1)]
- observation.is_documented_in_transcribed_content_id [bigint(20)]
- observation.is_of_observation_type_id [bigint(20)]
- observation.takes_place_during_event_id [bigint(20)]
- observation_type.id [bigint(20)]
- physical_unit.id [bigint(20)]
- transcribed_content.id [bigint(20)]
- transcribed_content.is_of_transcribed_content_type [bigint(20)]
- transcribed_content_type.id [bigint(20)]

**Comment by idali0226** [comment]
Hi Marks,

The schema was created by mysql workbench, and all the datatype are capitalised.

Ida


On 15 Sep 2017, at 10:43, Markus Englund <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #15<https://github.com/DINA-Web/dina-collections-data-model/issues/15> to @idali0226<https://github.com/idali0226>.

**Comment by idali0226** [comment]
Hi Markus,

I was wrong about the last email.

I am check the schema, the primary key is bigint(20), did I miss anything?

Ida
On 15 Sep 2017, at 10:43, Markus Englund <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #15<https://github.com/DINA-Web/dina-collections-data-model/issues/15> to @idali0226<https://github.com/idali0226>.

**Comment by jmenglund** [comment]
Sorry Ida, I checked against the wrong column. I'll get back as soon as I have modified my script...

**Comment by idali0226** [comment]
Ok.

Ida
On 15 Sep 2017, at 11:05, Markus Englund <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry Ida, I checked against the wrong column. I'll get back as soon as I have modified my script...

**Comment by jmenglund** [comment]
Now it looks much better with only one data type that is wrong (the correct data type inside square brackets):

- cataloged_unit.cataloged_by_text [varchar(255)]

**Comment by idali0226** [comment]
I already fix this.  I will upload into github after lunch.

Ida
On 15 Sep 2017, at 11:21, Markus Englund <notifications@github.com<mailto:notifications@github.com>> wrote:


Now it looks much better with only one data type that is wrong (the correct data type inside square brackets):

  *   cataloged_unit.cataloged_by_text [varchar(255)]

**Comment by jmenglund** [comment]
Great!

**Comment by jmenglund** [comment]
This issue is no longer valid since we will make changes to the specification.
