### ISSUE TITLE
What should we call the "first version" of the data model/schema?

### ISSUE THREAD

**Issue by jmenglund** [DINA-Web/dina-collections-data-model#16]
What should be the first release version of the data model and schema in this repo? We would like to use the same version for the data model as for the collection manager (https://github.com/DINA-Web/collections-ui). Should the first version that implements the new data model (and schema) then be called "0.2.0"?

**Comment by mikkohei13** [comment]
0.2.0 is ok with me. We are first concentrating on having automatic nightly (alpha) builds without tagged releases, so this doesn't have to be set in stone yet.
